version: "2"

linters:
  default: fast
  disable:
    - wsl
    - depguard
    - wsl_v5
    - cyclop
    - funlen
    - nlreturn
    - gochecknoinits
    - lll
    - mnd
    - testpackage
    - nestif
